name: deploy

inputs:
  - {name: model, type: Model}
  - {name: serving_image_uri, type: String}
  - {name: project, type: String}
  - {name: region, type: String}

implementation:
  container:
    image: ...
    command:
      - python
      - deploy.py
    args:
      - --model-uri
      - {inputUri: model}
      - --serving-image-uri
      - {inputValue: serving_image_uri}
      - --project
      - {inputValue: project}
      - --region
      - {inputValue: region}